language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2.5
  - 2.3.1

env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0"

matrix:
  exclude:
    - env: "RAILS_VERSION=3.2.0"
      rvm: 2.2.5
    - env: "RAILS_VERSION=3.2.0"
      rvm: 2.3.1
    - env: "RAILS_VERSION=5.0.0"
      rvm: 2.1
